### ISSUE TITLE
Question: Way to get millimeter positions of the hand that are not out of scale with respect to X, Y, and Z axis

### ISSUE THREAD

**Issue by TStod** [nok/leap-motion-processing#4]
I'm having trouble getting properly scaled points. Currently using move world and a external scalar to try and center the 0,0,0 on top of the leap and also have the z axis not horribly compressed.

**Comment by nok** [comment]
Hello @TStod,

you can use `getRawPosition()` to use the raw data in millimeters. On the other hand you can use `moveWorld()` ([here](https://github.com/nok/leap-motion-processing/blob/master/src/de/voidplus/leapmotion/LeapMotion.java#L275-L296)) to move the world globally, but then you have to use the `getPosition()` methods.

Happy coding,
Darius
