### ISSUE TITLE
Calls to getRoll() and getPitch() are switched

### ISSUE THREAD

**Issue by Axagthoth** [nok/leap-motion-processing#5]
Maybe it's not an issue but a matter of interpretation, but when comparing the names with the "traditional" airplane axes I find Roll and Pitch are switched. This is, I would expect getRoll() to return the angle when rotating around the axis going from the tips of my fingers to my wrist, while getPitch() should return the rotation around the axis going from my thumb to my pinky. Other than that, they work perfectly! It's just a matter of switching the function names.

**Comment by nok** [comment]
Hello @Axagthoth,

I tested it and you're right. I'm going to push an update with a fix today.

Thank you, and happy coding,
Darius
